### ISSUE TITLE
Changing react-router version  error

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-webclient#6]
react-routerのversionを4.0.0から3.0.5に下げました．
react-router v4~で書き直すよりも，v3.~のままで実行したほうが作業効率がいいと感じました．
しかし，コードをhtmlにマウントする時に，
`browser.js:49Warning: [react-router] Location "/Users/fmsurvivor/workspace/fabnavi/fabnavi-webclient/index.html" did not match any routes` というメッセージが表示されて，何も表示されません．これを解決することを優先します．

因みに，マウントするファイルを `./src/components/FabnaviApp.jsx` から `./src/App.jsx` にすると正しく実行されます

**Comment by hrl7** [comment]
これはReactRouterのバージョンの問題ではない。
BrowserHistory使ってるのが問題。HashRouterかMemoryRouterつかって。
古いやつなら, HashHistoryかMemoryHistoryかな

**Comment by fmsuvM** [comment]
HashHistoryを使うことで解決
