### ISSUE TITLE
Player Modeに遷移出来ない

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-webclient#7]
fabnaviのホームが表示されてキー操作でプロジェクトを選べるが，プロジェクトを選択後，playをEnterしてもPlayer Modeに遷移しない
Debugには `project not loaded!` と出力される
コンソールには `Uncaught TypeError: Cannot read property 'location' of undefined`と `Uncaught TypeError: Cannot read property '_currentElement' of null` と表示される
また，escで脱出出来ず， `ReactReconciler.js:63 Uncaught TypeError: Cannot read property 'getHostNode' of null` というエラーが出力される

**Comment by hrl7** [comment]
`Uncaught TypeError: Cannot read property 'location' of undefined` は何がundefinedなんだろう？

**Comment by fmsuvM** [comment]
Delete-CHANGE_FRAME branchで遷移方法ごと変更
propの中身の参照する場所を変更
